services:
  scfront:
    build:
      context: ./scFront
      dockerfile: Dockerfile
    container_name: scfront
    ports:
      - "5173:5173"
    volumes:
      - ./scFront:/app
      # Le dossier node_modules local ne sera PAS copié dans le container
      # Car le volume anonyme masque le dossier node_modules monté depuis l'hôte
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${PROJECT_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 4444:80
    environment:
      PMA_HOST: mysql
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mysql

volumes:
  mysql_data:
