services:
  scfront:
    build:
      context: ./scFront
      dockerfile: Dockerfile
    container_name: scfront
    ports:
      - "5173:5173"
    volumes:
      - ./scFront:/app
      # Le dossier node_modules local ne sera PAS copié dans le container
      # Car le volume anonyme masque le dossier node_modules monté depuis l'hôte
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
    command: npm run dev -- --host 0.0.0.0

  jenkins:
    build:
      context: .
      dockerfile: jenkins.dockerfile
    container_name: scJenkins
    depends_on:
      - sonarqube
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    restart: unless-stopped


volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
